### PR TITLE
Update for OpenTracing1.5.0

### PR DESCRIPTION
**Pull request by gabrielkay**
Modeled after https://github.com/lightstep/lightstep-tracer-cpp/pull/105

### CODE REVIEW

**Comment by rnburn** [comment]
Thanks. Looks good.

Could you just run `scripts/run_clang_format.sh` ?

**Comment by gabrielkay** [comment]
Is this what you meant?

**Comment by rnburn** [comment]
Yep, I think the only thing missing is the bazel commit [here](https://github.com/rnburn/zipkin-cpp-opentracing/blob/master/WORKSPACE#L6); then it should be good to merge.

**Comment by gabrielkay** [comment]
I put in the latest commit hash

**Comment by rnburn** [comment]
👍 - thank you

**Comment by gabrielkay** [comment]
Any idea why I now get this error when doing a make???

/home/gabrielk/june27/zipkin-cpp-opentracing/zipkin_opentracing/src/dynamic_load.cc:22:44: error: ‘OPENTRACING_ABI_VERSION’ was not declared in this scope
   if (std::strcmp(opentracing_abi_version, OPENTRACING_ABI_VERSION) != 0) {
                                            ^
/home/gabrielk/june27/zipkin-cpp-opentracing/zipkin_opentracing/src/dynamic_load.cc:28:21: error: expected ‘;’ before ‘OPENTRACING_ABI_VERSION’
         "expected " OPENTRACING_ABI_VERSION " but got ";
                     ^
/home/gabrielk/june27/zipkin-cpp-opentracing/zipkin_opentracing/src/dynamic_load.cc: At global scope:
/home/gabrielk/june27/zipkin-cpp-opentracing/zipkin_opentracing/src/dynamic_load.cc:41:33: error: expected constructor, destructor, or type conversion before ‘(’ token
 OPENTRACING_DECLARE_IMPL_FACTORY(OpenTracingMakeTracerFactoryFunction)
                                 ^
make[2]: *** [zipkin_opentracing/CMakeFiles/zipkin_opentracing-static.dir/src/dynamic_load.cc.o] Error 1
make[1]: *** [zipkin_opentracing/CMakeFiles/zipkin_opentracing-static.dir/all] Error 2

**Comment by rnburn** [comment]
Maybe you have a pre-1.5 build of opentracing installed that doesn't have OPENTRACING_ABI_VERSION installed

**Pull request merged**
